package com.javaweb.event_management_backend.BookingManagement.mappers;

import com.javaweb.event_management_backend.BookingManagement.dtos.response.PaymentResponseDto;
import com.javaweb.event_management_backend.BookingManagement.models.Payment;
import com.javaweb.event_management_backend.EventCatalogue.models.Event;
import org.springframework.stereotype.Component;

@Component
public class PaymentMapper {

    // Entity → DTO
    public PaymentResponseDto.PaymentResult toPaymentResult(Payment payment, String message) {
        return PaymentResponseDto.PaymentResult.builder()
                .paymentId(payment.getPaymentId())
                .amount(payment.getAmount())
                .paymentMethod(payment.getPaymentMethod())
                .status(payment.getStatus())
                .paymentDate(payment.getPaymentDate())
                .bookingId(payment.getBooking().getBookingId())
                .message(message)
                .build();
    }

    public PaymentResponseDto.AdminView toAdminView(Payment payment) {

        // navigate chain to get event
        // payment → booking → issuedTickets → first ticket → ticketType → event

        Event event = payment.getBooking()
                .getIssuedTickets()
                .get(0)
                .getTicketType()
                .getEvent();

        // get attendee info from booking → user
        String attendeeName = payment.getBooking().getUser().getFirstName()
                + " " + payment.getBooking().getUser().getLastName();

        return PaymentResponseDto.AdminView.builder()
                .paymentId(payment.getPaymentId())
                .amount(payment.getAmount())
                .paymentMethod(payment.getPaymentMethod())
                .status(payment.getStatus())
                .paymentDate(payment.getPaymentDate())
                .bookingId(payment.getBooking().getBookingId())
                .attendeeName(attendeeName)
                .attendeeEmail(payment.getBooking().getUser().getEmail())
                .eventTitle(event.getTitle())
                .build();
    }

    // No toEntity here — payments are never created
    // manually. They are generated by the service
    // layer after a booking is confirmed
}