package com.javaweb.event_management_backend.EventCatalogue.mappers;

import com.javaweb.event_management_backend.EventCatalogue.dtos.response.IssuedTicketResponseDto;
import com.javaweb.event_management_backend.EventCatalogue.models.IssuedTicket;
import org.springframework.stereotype.Component;

@Component
public class IssuedTicketMapper {

    // Entity → DTO
    public IssuedTicketResponseDto.Response toResponse(IssuedTicket issuedTicket) {
        return IssuedTicketResponseDto.Response.builder()
                .issuedTicketId(issuedTicket.getIssuedTicketId())
                .qrCode(issuedTicket.getQrCode())
                .ticketCode(issuedTicket.getTicketCode())
                .status(issuedTicket.getStatus())
                .issuedAt(issuedTicket.getIssuedAt())
                .ticketTypeName(issuedTicket.getTicketType().getName())
                .ticketTypePrice(issuedTicket.getTicketType().getPrice())
                .attendeeName(issuedTicket.getBooking().getUser().getFirstName() + " " + issuedTicket.getBooking().getUser().getLastName())
                .attendeeEmail(issuedTicket.getBooking().getUser().getEmail())
                .eventTitle(issuedTicket.getTicketType().getEvent().getTitle())
                .build();
    }

    // Used at the door when organizer verifies a ticket
    public IssuedTicketResponseDto.VerificationResult toVerificationResult(IssuedTicket issuedTicket) {

        // determine if ticket is valid
        boolean isValid = issuedTicket.getStatus() ==
                com.javaweb.event_management_backend.EventCatalogue.enums.IssuedTicketStatus.VALID;

        // build human readable message based on status
        String message = switch (issuedTicket.getStatus()) {
            case VALID -> "Entry granted";
            case USED -> "Ticket already scanned";
            case CANCELLED -> "Ticket has been cancelled";
        };

        // get attendee full name from booking → user
        String attendeeName = issuedTicket.getBooking().getUser().getFirstName()
                + " " + issuedTicket.getBooking().getUser().getLastName();

        // get event title from ticketType → event
        String eventTitle = issuedTicket.getTicketType().getEvent().getTitle();

        return IssuedTicketResponseDto.VerificationResult.builder()
                .issuedTicketId(issuedTicket.getIssuedTicketId())
                .ticketCode(issuedTicket.getTicketCode())
                .status(issuedTicket.getStatus())
                .isValid(isValid)
                .attendeeName(attendeeName)
                .eventTitle(eventTitle)
                .ticketTypeName(issuedTicket.getTicketType().getName())
                .issuedAt(issuedTicket.getIssuedAt())
                .message(message)
                .build();
    }

    // No toEntity here — IssuedTickets are never
    // created manually. They are generated by the
    // service layer after a successful payment
}