spring.application.name=event-management-backend
spring.datasource.url=jdbc:mysql://mysql-eventmanagement1-kelinguma-ce4.b.aivencloud.com:27472/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_i5CnDi3pQ8hbhfibvn5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS10aGF0LWlzLWxvbmctZW5vdWdo
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs