spring.application.name=event-management-backend

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://avnadmin:AVNS_i5CnDi3pQ8hbhfibvn5@mysql-eventmanagement1-kelinguma-ce4.b.aivencloud.com:27472/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_i5CnDi3pQ8hbhfibvn5}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server
server.port=${PORT:8082}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS10aGF0LWlzLWxvbmctZW5vdWdo}
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:kfutwahnguma.0.2@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:kfutwah2005}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File upload
server.tomcat.max-http-form-post-size=20971520
server.tomcat.max-swallow-size=20971520
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# CORS
cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}